### ISSUE TITLE
Bulk Edit not working in V11

### ISSUE THREAD

**Issue by Gabbaoma** [Mallander/playlist-enhancer#18]
Hi there, I love you module. Sadly the bulk edit function stopped working in V11, at least for me. Will you be updating the module?

Here is a console error when trying to bulk edit a playlist:
`module.js:295  Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'getEmbeddedCollection')
[Detected 1 package: playlist-enhancer]
    at bulkEditTracks (module.js:295:32)
    at Dialog.callback (module.js:281:7)
    at Dialog.submit (foundry.js:64797:46)
    at Dialog._onClickButton (foundry.js:64725:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)`

Thank you!

**Comment by iansutherland75** [comment]
Confirmed the same behaviour
